trigger:
  branches:
    include:
      - main

variables:
- group: AWS CREDENTIALS  # 👈 This links the variable group you created

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build React App'

- script: |
    # Install or update AWS CLI
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install --update

    # Deploy to S3 (use dist for Vite builds)
    aws s3 sync ./dist s3://pragma-challenge-frontend-hosting --delete --region us-west-2
  displayName: 'Deploy to S3'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)